# Generated by Django 4.2.2 on 2023-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeleft',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
