# Generated by Django 4.2.2 on 2023-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_task_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(),
        ),
    ]
